### ISSUE TITLE
بستن یک تاریخ خاص

### ISSUE THREAD

**Issue by imelyas** [xclud/persian_flutter#1]
سلام
ببخشید من میخواستم یه سری روزهای خاص رو ببندم
مثلا بگم پنج شنبه و جمع یا مثلا یه روز خاص رو نشه انتخاب کرد
ممنون میشم راهنمایی کنید کجاشو باید تغییر بدم
تشکر

**Comment by xclud** [comment]
@elyasbeshkani Unfortunately this is not possible yet. I put this feature in my backlog and once it's implemented i will notify you.

Meanwhile, please feel free to fork and implement this feature by your own and make a PR when you get it to work.

I am closing this issue but please do not hesitate to open a new issue if needed.
